### ISSUE TITLE
Validation fails when schema is loaded from String but succeeds when loaded from URL?

### ISSUE THREAD

**Issue by the4thamigo-uk** [xeipuuv/gojsonschema#170] opened 2017-12-14 12:37 UTC
I am validating my schema against the v4 JSON meta-schema. When I include `anyOf, I get a successful validation when I load the meta schema from a URL, but when I load the same meta-schema from a string validation fails!

Also, the results from LoadJSON() for both meta-schema JSONLoader instances compare as equal!

Is this a bug or am I doing something wrong?

```
package main

import (
	"fmt"
	"github.com/xeipuuv/gojsonschema"
	"reflect"
)

var schemaData = `
{
	"type": "object",
	"properties": {
		"test": {
			"anyOf": [
			{ "type": "integer" }
			]
		}
	}
}
`

var metaSchemaData = `
{
    "id": "http://json-schema.org/draft-04/schema#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "Core schema meta-schema",
    "definitions": {
        "schemaArray": {
            "type": "array",
            "minItems": 1,
            "items": { "$ref": "#" }
        },
        "positiveInteger": {
            "type": "integer",
            "minimum": 0
        },
        "positiveIntegerDefault0": {
            "allOf": [ { "$ref": "#/definitions/positiveInteger" }, { "default": 0 } ]
        },
        "simpleTypes": {
            "enum": [ "array", "boolean", "integer", "null", "number", "object", "string" ]
        },
        "stringArray": {
            "type": "array",
            "items": { "type": "string" },
            "minItems": 1,
            "uniqueItems": true
        }
    },
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "format": "uri"
        },
        "$schema": {
            "type": "string",
            "format": "uri"
        },
        "title": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "default": {},
        "multipleOf": {
            "type": "number",
            "minimum": 0,
            "exclusiveMinimum": true
        },
        "maximum": {
            "type": "number"
        },
        "exclusiveMaximum": {
            "type": "boolean",
            "default": false
        },
        "minimum": {
            "type": "number"
        },
        "exclusiveMinimum": {
            "type": "boolean",
            "default": false
        },
        "maxLength": { "$ref": "#/definitions/positiveInteger" },
        "minLength": { "$ref": "#/definitions/positiveIntegerDefault0" },
        "pattern": {
            "type": "string",
            "format": "regex"
        },
        "additionalItems": {
            "anyOf": [
                { "type": "boolean" },
                { "$ref": "#" }
            ],
            "default": {}
        },
        "items": {
            "anyOf": [
                { "$ref": "#" },
                { "$ref": "#/definitions/schemaArray" }
            ],
            "default": {}
        },
        "maxItems": { "$ref": "#/definitions/positiveInteger" },
        "minItems": { "$ref": "#/definitions/positiveIntegerDefault0" },
        "uniqueItems": {
            "type": "boolean",
            "default": false
        },
        "maxProperties": { "$ref": "#/definitions/positiveInteger" },
        "minProperties": { "$ref": "#/definitions/positiveIntegerDefault0" },
        "required": { "$ref": "#/definitions/stringArray" },
        "additionalProperties": {
            "anyOf": [
                { "type": "boolean" },
                { "$ref": "#" }
            ],
            "default": {}
        },
        "definitions": {
            "type": "object",
            "additionalProperties": { "$ref": "#" },
            "default": {}
        },
        "properties": {
            "type": "object",
            "additionalProperties": { "$ref": "#" },
            "default": {}
        },
        "patternProperties": {
            "type": "object",
            "additionalProperties": { "$ref": "#" },
            "default": {}
        },
        "dependencies": {
            "type": "object",
            "additionalProperties": {
                "anyOf": [
                    { "$ref": "#" },
                    { "$ref": "#/definitions/stringArray" }
                ]
            }
        },
        "enum": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true
        },
        "type": {
            "anyOf": [
                { "$ref": "#/definitions/simpleTypes" },
                {
                    "type": "array",
                    "items": { "$ref": "#/definitions/simpleTypes" },
                    "minItems": 1,
                    "uniqueItems": true
                }
            ]
        },
        "allOf": { "$ref": "#/definitions/schemaArray" },
        "anyOf": { "$ref": "#/definitions/schemaArray" },
        "oneOf": { "$ref": "#/definitions/schemaArray" },
        "not": { "$ref": "#" }
    },
    "dependencies": {
        "exclusiveMaximum": [ "maximum" ],
        "exclusiveMinimum": [ "minimum" ]
    },
    "default": {}
}
`

func main() {
	ls := gojsonschema.NewStringLoader(schemaData)
	lm1 := gojsonschema.NewReferenceLoader("http://json-schema.org/draft-04/schema")
	lm2 := gojsonschema.NewStringLoader(metaSchemaData)

	d1, _ := lm1.LoadJSON()
	d2, _ := lm2.LoadJSON()
	fmt.Println(reflect.DeepEqual(d1, d2))

	result, err := gojsonschema.Validate(lm1, ls)
	fmt.Println(err)
	fmt.Println(result.Valid())
	result, err = gojsonschema.Validate(lm2, ls)
	fmt.Println(err)
	fmt.Println(result.Valid())
	fmt.Println(result.Errors())
}
```
The above code outputs : 
```
true
<nil>
true
<nil>
false
[properties.anyOf.0: Invalid type. Expected: array, given: object]
```

**Comment by johandorland** [comment] 2017-12-14 14:18
It's a bug related to ```$ref```` parsing which is handled differently when loading from a raw string instead of a url. I'll submit a fix over the weekend if I can clean up the PR which I have locally right now.

**Comment by the4thamigo-uk** [comment] 2017-12-14 14:43
Great, thanks for confirming. I ws trying to debug it, but I'm unfamiliar with the code. :)

**Comment by notjames** [comment] 2017-12-20 18:11
@johandorland thank you for your help!

**Comment by the4thamigo-uk** [comment] 2018-01-11 12:15
Hmm, the latest code doesnt seem to fix my issue. The url and raw string versions are now consistent, but both fail to validate my example schema. Ive also tried a few other schemas containing `allOf`, `oneOf` etc from various web sites and I get validation failures as well. Error is : 

```
Expected: array, given: object
```

**Comment by johandorland** [comment] 2018-01-11 18:22
The code also depends on https://github.com/xeipuuv/gojsonreference/pull/8 in the underlying jsonreference library. That pull request has not been merged yet.

**Comment by andy-miracl** [comment] 2018-01-16 10:05
@xeipuuv sorry for the cross-post but is there any chance we can merge https://github.com/xeipuuv/gojsonreference/pull/8 because currently https://github.com/xeipuuv/gojsonschema/pull/171 has resulted in a regression (not even loading the meta schema from a URL works anymore).

**Closed** 2018-02-06 13:42 UTC
