### ISSUE TITLE
Filename with spaces in jsonLoader

### ISSUE THREAD

**Issue by benoitTremblay** [xeipuuv/gojsonschema#94] opened 2016-01-08 18:04 UTC
jsonLoader replaces %20 by spaces for filename under windows but does not do it under linux  (or it might be windows directory mounted in a linux VM).
I suggest the following change to handle space under all operating systems:

```
diff --git a/jsonLoader.go b/jsonLoader.go
index a9458a8..6fc31d5 100644
--- a/jsonLoader.go
+++ b/jsonLoader.go
@@ -87,9 +87,9 @@ func (l *jsonReferenceLoader) loadJSON() (interface{}, error) {
                                filename = filename[1:]
                        }
                        filename = filepath.FromSlash(filename)
-                       filename = strings.Replace(filename, "%20", " ", -1)
                }

+               filename = strings.Replace(filename, "%20", " ", -1)
                document, err = l.loadFromFile(filename)
                if err != nil {
                        return nil, err

```

**Comment by kajf** [comment] 2019-10-09 12:43
@xeipuuv 
it looks like the fix for this issue was overriden by 
https://github.com/xeipuuv/gojsonschema/commit/6cd6dcbc9e7514bea255a9241665a6c2d0b37fb4
so issue is back again in 1.1.0

can we reopen this bug and maybe review/reapply the fix?

**Comment by johandorland** [comment] 2019-10-09 14:59
Ok.

1. I need to figure out what edge case https://github.com/xeipuuv/gojsonschema/commit/6cd6dcbc9e7514bea255a9241665a6c2d0b37fb4 fixed, because a plain revert will probably break other things.
2. Next time include a unit test, because this is exactly why you have them.

**Comment by kajf** [comment] 2019-10-09 16:35
Maybe I can help with that. 
The edge case is having filename like 'file://with spaces/abc' converted to 'file://with%20spaces/abc' since refToUrl.String() does URL encoding

As a result LoadJSON() fails with 'The system cannot find the path specified.'

The fix was to prevent encoding by using refToUrl.GetUrl().Path

Totally agree about unit testing though extracting that logic to avoid file operations is more invasive change. I can work on new pull request if you like

**Comment by johandorland** [comment] 2019-10-09 16:46
The original reason for https://github.com/xeipuuv/gojsonschema/commit/6cd6dcbc9e7514bea255a9241665a6c2d0b37fb4 was that if you only look at the path some other functionality doesn't work (https://github.com/xeipuuv/gojsonschema/blob/6a016cf16650f6be7151db7c3be6fc90a2c4d9b1/schema_test.go#L239). With a `NewReferenceLoader) you can also reference at a subdocument within the file and use that as a schema. This was a feature added a while back. If you then only look at the path this doesn't work as you throw away the fragment, so you need the full URL with the `refToUrl.String()`.

To get the decoded string I opted for manually decoding the URL. You can take a look at the PR and if you have any suggestions or improvements let me know.

**Comment by johandorland** [comment] 2019-10-10 16:48
The new version of gojsonschema is coming out as soon as I feel like making release notes. On a more serious note quite a few bug fixes have gone in since the last release, so when I'll probably double check the PR and write release notes soon™.

**Closed** 2019-10-15 14:03 UTC
Labels: bug

**Comment by johandorland** [comment] 2019-10-15 16:06
A new release with the included fix has just been released.

**Comment by kajf** [comment] 2019-10-24 10:54
@johandorland thanks for the release
unfortunately it seems another regression has been introduced: now '+' symbols in file names does not seem to be interpreted correctly

see failing test in patch
[files_with_'+'_symbols.patch.txt](https://github.com/xeipuuv/gojsonschema/files/3767108/files_with_.%2B._symbols.patch.txt)
